[theme]
base = "light"
primaryColor = "#055e82"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fb"
textColor = "#2b3d50"
font = "sans serif"

[client]
showSidebarNavigation = true
showErrorDetails = true
toolbarMode = "auto"

[runner]
magicEnabled = true
fastReruns = true
fixMatplotlib = true
installTracer = false
postScriptGC = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s: %(message)s"
enableRich = true

[deprecation]
showPyplotGlobalUse = false
showfileUploaderEncoding = false

[ui]
hideTopBar = false
hideSidebarNav = false